# Generated by Django 5.2.5 on 2025-08-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixp_tracker', '0015_statsperixp_monthly_members_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='peering_policy',
            field=models.CharField(choices=[('open', 'Open'), ('selective', 'Selective'), ('restrictive', 'Restrictive'), ('no', 'No')], default='', max_length=50),
        ),
    ]
