# Generated by Django 5.2.5 on 2025-09-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixp_tracker', '0017_ixp_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='roa_v4_invalid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asn',
            name='roa_v4_unknown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asn',
            name='roa_v4_valid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asn',
            name='roa_v6_invalid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asn',
            name='roa_v6_unknown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asn',
            name='roa_v6_valid',
            field=models.IntegerField(default=0),
        ),
    ]
