# Generated by Django 5.2.5 on 2025-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixp_tracker', '0017_ixp_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='rpki_counts_by_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='asn',
            name='rpki_counts_by_roa',
            field=models.JSONField(default=dict),
        ),
    ]
