# Generated by Django 5.2.5 on 2025-10-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixp_tracker', '0018_ixp_anchor_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixp',
            name='physical_locations',
            field=models.IntegerField(null=True),
        ),
    ]
