# Generated by Django 6.0.4 on 2026-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0020_ixp_physical_locations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ISOCId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregate_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "ISOC id mapping",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("aggregate_id",), name="ixp_tracker_aggregate_isoc_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregate_id", models.UUIDField()),
                ("aggregate_type", models.TextField()),
                ("event_date", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.TextField()),
                ("event_sequence", models.IntegerField()),
                ("data", models.JSONField()),
            ],
            options={
                "verbose_name": "Stored event",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("aggregate_id", "event_sequence"),
                        name="ixp_tracker_aggregate_sequence",
                    )
                ],
            },
        ),
    ]
