# Generated by Django 6.0.4 on 2026-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0021_isocid_storedevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="IXPIdMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregate_id", models.UUIDField()),
                ("peeringdb_id", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "ISOC id mapping",
            },
        ),
        migrations.RemoveConstraint(
            model_name="isocid",
            name="ixp_tracker_aggregate_isoc_id",
        ),
        migrations.DeleteModel(
            name="ISOCId",
        ),
        migrations.AddConstraint(
            model_name="ixpidmap",
            constraint=models.UniqueConstraint(
                fields=("aggregate_id",), name="ixp_tracker_aggregate_isoc_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="ixpidmap",
            constraint=models.UniqueConstraint(
                fields=("peeringdb_id",), name="ixp_tracker_aggregate_peeringdb_id"
            ),
        ),
    ]
