# Generated by Django 6.0.4 on 2026-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ixp_tracker",
            "0022_ixpidmap_remove_isocid_ixp_tracker_aggregate_isoc_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ASNMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregate_id", models.UUIDField()),
                ("asn", models.IntegerField()),
            ],
            options={
                "verbose_name": "ASN mapping",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("aggregate_id",),
                        name="ixp_tracker_asn_map_aggregate_id",
                    ),
                    models.UniqueConstraint(
                        fields=("asn",), name="ixp_tracker_asn_map_asn"
                    ),
                ],
            },
        ),
    ]
