# Generated by Django 6.0.5 on 2026-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixp_tracker', '0023_asnmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXPASNMemberMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_id', models.UUIDField()),
                ('ixp_id', models.UUIDField()),
                ('asn_id', models.UUIDField()),
            ],
            options={
                'verbose_name': 'IXP ASN member mapping',
                'constraints': [models.UniqueConstraint(fields=('aggregate_id',), name='ixp_tracker_ixp_asn_member_map_aggregate_id'), models.UniqueConstraint(fields=('ixp_id',), name='ixp_tracker_ixp_asn_member_map_ixp_id'), models.UniqueConstraint(fields=('asn_id',), name='ixp_tracker_ixp_asn_member_map_asn_id')],
            },
        ),
    ]
