# Generated by Django 6.0.4 on 2026-06-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0023_asnmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregateSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregate_id", models.UUIDField()),
                ("event_sequence", models.IntegerField()),
                ("snapshot_date", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
            ],
            options={
                "verbose_name": "Aggregate snapshot",
                "ordering": ["-event_sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("aggregate_id", "event_sequence"),
                        name="ixp_tracker_snapshot_aggregate_sequence",
                    )
                ],
            },
        ),
    ]
