# Generated by Django 6.0.4 on 2026-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixp_tracker', '0023_asnmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXPMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ixp_id', models.UUIDField()),
                ('asn', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('date_left', models.DateTimeField(null=True)),
                ('is_rs_peer', models.BooleanField()),
                ('port_speed', models.IntegerField()),
            ],
            options={
                'verbose_name': 'IXP members',
                'constraints': [models.UniqueConstraint(fields=('ixp_id', 'asn'), name='ixp_tracker_ixp_members')],
            },
        ),
    ]
