# Generated by Django 6.0.4 on 2026-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0024_aggregatesnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedevent",
            name="event_date",
            field=models.DateTimeField(),
        ),
    ]
