# Generated by Django 6.0.4 on 2026-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0025_alter_aggregatesnapshot_snapshot_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatsPerIXPES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ixp", models.IntegerField()),
                ("stats_date", models.DateField()),
                ("capacity", models.FloatField()),
                ("members", models.IntegerField()),
                ("domestic_network_membership", models.FloatField()),
                ("domestic_network_coverage", models.FloatField()),
                ("rs_peering_rate", models.FloatField()),
                ("members_joined_last_12_months", models.IntegerField()),
                ("members_left_last_12_months", models.IntegerField()),
                ("monthly_members_change", models.IntegerField()),
                ("monthly_members_change_percent", models.FloatField()),
                ("last_generated", models.DateTimeField()),
            ],
            options={
                "verbose_name": "IXP stats",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ixp", "stats_date"),
                        name="ixp_tracker_es_unique_ixp_stats",
                    )
                ],
            },
        ),
    ]
