# Generated by Django 6.0.4 on 2026-06-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0026_statsperixpes"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatsPerCountryES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("stats_date", models.DateField()),
                ("ixp_count", models.IntegerField()),
                ("routed_asn_count", models.IntegerField()),
                ("member_count", models.IntegerField()),
                ("domestic_network_membership", models.FloatField()),
                ("domestic_network_coverage", models.FloatField()),
                ("total_capacity", models.FloatField()),
                ("last_generated", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Per-country stats",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "stats_date"),
                        name="ixp_tracker_unique_per_country_stats_es",
                    )
                ],
            },
        ),
    ]
