# Generated by Django 6.0.4 on 2026-06-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0027_statspercountryes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdatedIXPs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregate_id", models.UUIDField()),
                ("last_updated", models.DateField()),
                ("isoc_id", models.IntegerField()),
                ("data", models.JSONField()),
            ],
            options={
                "verbose_name": "Last updated IXPs",
                "ordering": ["isoc_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("aggregate_id",), name="ixp_tracker_last_updated_ixps"
                    )
                ],
            },
        ),
    ]
