# Generated by Django 6.0.4 on 2026-06-26 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0028_updatedixps"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StatsPerCountry",
            new_name="StatsPerCountryLegacy",
        ),
        migrations.RenameModel(
            old_name="StatsPerIXP",
            new_name="StatsPerIXPLegacy",
        ),
    ]
