# Generated by Django 6.0.4 on 2026-06-26 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0029_rename_statspercountry_statspercountrylegacy_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StatsPerCountryES",
            new_name="StatsPerCountry",
        ),
        migrations.RenameModel(
            old_name="StatsPerIXPES",
            new_name="StatsPerIXP",
        ),
    ]
