# Generated by Django 6.0.4 on 2026-07-23 10:38

import ixp_tracker.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0030_rename_statspercountryes_statspercountry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedevent",
            name="data",
            field=models.JSONField(
                decoder=ixp_tracker.json.OrJSONSerializer,
                encoder=ixp_tracker.json.OrJSONSerializer,
            ),
        ),
    ]
