# Generated by Django 6.0.4 on 2026-07-24 14:43

from django.db import migrations, models
from ixp_tracker import json


class Migration(migrations.Migration):
    dependencies = [
        ("ixp_tracker", "0030_rename_statspercountryes_statspercountry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aggregatesnapshot",
            name="data",
            field=models.JSONField(encoder=json.IXPJSONEncoder),
        ),
        migrations.AlterField(
            model_name="storedevent",
            name="data",
            field=models.JSONField(encoder=json.IXPJSONEncoder),
        ),
        migrations.AlterField(
            model_name="updatedixps",
            name="data",
            field=models.JSONField(encoder=json.IXPJSONEncoder),
        ),
    ]
