# Generated by Django 6.0.7 on 2026-08-18 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ixp_tracker",
            "0031_alter_aggregatesnapshot_data_alter_storedevent_data_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="asn",
            name="ixp_tracker_unique_as_number",
        ),
        migrations.RemoveConstraint(
            model_name="ixp",
            name="ixp_tracker_unique_ixp_peeringdb_id",
        ),
        migrations.RemoveConstraint(
            model_name="ixpmember",
            name="ixp_tracker_unique_ixp_membership",
        ),
        migrations.RemoveField(
            model_name="ixpmembershiprecord",
            name="member",
        ),
        migrations.RemoveConstraint(
            model_name="statspercountrylegacy",
            name="ixp_tracker_unique_per_country_stats",
        ),
        migrations.DeleteModel(
            name="StatsPerCountryLegacy",
        ),
        migrations.RemoveConstraint(
            model_name="statsperixplegacy",
            name="ixp_tracker_unique_ixp_stats",
        ),
        migrations.RemoveField(
            model_name="ixpmember",
            name="asn",
        ),
        migrations.RemoveField(
            model_name="ixpmember",
            name="ixp",
        ),
        migrations.DeleteModel(
            name="IXPMembershipRecord",
        ),
        migrations.RemoveField(
            model_name="statsperixplegacy",
            name="ixp",
        ),
        migrations.DeleteModel(
            name="ASN",
        ),
        migrations.DeleteModel(
            name="IXPMember",
        ),
        migrations.DeleteModel(
            name="IXP",
        ),
        migrations.DeleteModel(
            name="StatsPerIXPLegacy",
        ),
    ]
